### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by qian-liu** [SpiNNakerManchester/SpiNNakerManchester.github.io#1]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb0 in position 1: ordinal not in range(128)

To solve it,
Edit C:\Python27\Lib\mimetypes.py this file:
Add these codes
if sys.getdefaultencoding() != 'gbk':
    reload(sys)
    sys.setdefaultencoding('gbk')
before the following line
default_encoding = sys.getdefaultencoding()

**Comment by alan-stokes** [comment]
your solution was added to the trouble shooting guide now placed at the end of the installation guides. 

thank you for reporting this and giving us the solution. 

Alan
