### ISSUE TITLE
default params reported in lab manual wrong

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/SpiNNakerManchester.github.io#10]
the default params reported in the "running PyNN sims on SpiNNaker" are incorrect with PyNN and the source code. for one, they report that v_reset and v_rest are different, where in actuality they are the same. 

This should be changed by the next workshop.

**Comment by andrewgait** [comment]
Fixed by https://github.com/SpiNNakerManchester/SpiNNakerManchester.github.io/pull/22

**Comment by alan-stokes** [comment]
fixed in master
