### ISSUE TITLE
Spinn_common install misses sqrt.h

### ISSUE THREAD

**Issue by nicolasgazeres** [SpiNNakerManchester/SpiNNakerManchester.github.io#11]
Hi team,
The spinn_common-3.0.0 package used in the Lab comes with a number of files in the include/ directory.
All these files are copied over during "make install" except one, sqrt.h
Either sqrt.h is missing in the HEADERS variable or it's useless in include/ directory.
Regards,
Nicolas

**Comment by rowleya** [comment]
It isn't needed by anything as yet, but it is part of the library and so should be copied over.

**Comment by andrewgait** [comment]
Fixed by https://github.com/SpiNNakerManchester/spinn_common/pull/11
