### ISSUE TITLE
spinn_common's Makefile takes default goal in spinnaker_tools

### ISSUE THREAD

**Issue by nicolasgazeres** [SpiNNakerManchester/SpiNNakerManchester.github.io#12]
Hi team,
On my system (Win7 / GNU Make 3.81), make in the spinn_common directory produces the following message:

make: *** No rule to make target `build/gnu/_build.o', needed by `build/gnu/.elf'.  Stop.

This is presumably because the Default Goal used is the one that is (first) found in the included Spinnaker_tools Makefile.

On my system, I find that the attached modified Makefile, in which the declarations of OBJS, BUILD_OBJS and default build rule libspinn_common.a have been pushed up a few lines removes the problem.

What is your opinion on the symptom and would the change be compatible with your systems ?

Thanks & Regards,
Nicolas
[Makefile.patch.txt](https://github.com/SpiNNakerManchester/SpiNNakerManchester.github.io/files/642703/Makefile.patch.txt)

**Comment by rowleya** [comment]
This is fine in theory - in practice we would need to check this works on all platforms.

**Comment by andrewgait** [comment]
Has anyone built in Windows 7 recently to test this?  Is it worth changing the build structure like this for an operating system which is out of mainstream support but still in extended support?
