### ISSUE TITLE
front_end_common_lib install misses eieio_interface.h

### ISSUE THREAD

**Issue by nicolasgazeres** [SpiNNakerManchester/SpiNNakerManchester.github.io#13]
Hi team,
The SpiNNFrontEndCommon-3.0.0 package used in the Lab comes with a number of files in the front_end_common_lib/include/ directory.
All these files are copied over during "make install" except one, eieio_interface.h
Either eieio_interface.h is missing in the HEADERS variable or it's useless in include/ directory.
Regards,
Nicolas

**Comment by rowleya** [comment]
From what I can see, the file isn't used and therefore should be removed.  I will check further...

**Comment by andrewgait** [comment]
As far as I can tell, this is unused and should be removed.

**Comment by andrewgait** [comment]
Fixed by https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/179

**Comment by alan-stokes** [comment]
closed
