### ISSUE TITLE
python pip install v not working in windows

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/SpiNNakerManchester.github.io#16]
http://spinnakermanchester.github.io/development/devenv.html#PythonRequirements

Line:
pip install ... "spalloc>=v0.2.2,<v1.0.0" ...

In windows the version numbers with v do not work.

replace with:
pip install ... "spalloc>=0.2.2,<1.0.0" ...

Then it works

Note: In windows the command is of course python -m pip ...

**Comment by rowleya** [comment]
Yes, this is a weird issue - I think that the version should be 0.2.2, and that the v should be removed, but we must have had issues in the past with this.  I will have to investigate again and see what has gone wrong...

Note that on windows, pip install should work - you shouldn't need to do python -m pip.  The installation of pip should create a pip.exe file in C:\Python27\Scripts I think.

**Comment by Christian-B** [comment]
Agree pip.exe has been installed and does work in windows

But
 pip install "spalloc>=v0.2.2,<v1.0.0"

Still fails.

**Comment by Christian-B** [comment]
Works with the v in fedora

**Comment by alan-stokes** [comment]
also worksd with v in ubuntu

**Comment by rowleya** [comment]
It probably depends on the pip version - does it work without the v in fedora and ubuntu?  If so, we can just remove the v...

**Comment by alan-stokes** [comment]
least in ubuntu. yep

**Comment by andrewgait** [comment]
Fixed with https://github.com/SpiNNakerManchester/SpiNNakerManchester.github.io/pull/25

**Comment by alan-stokes** [comment]
closed
