### ISSUE TITLE
RunningPyNNSimulationsonSpiNNaker-LabManual.pdf errors

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/SpiNNakerManchester.github.io#17]
In http://spinnakermanchester.github.io/spynnaker/3.0.0/RunningPyNNSimulationsonSpiNNaker-LabManual.pdf

Suggestion: Add:
try:
    import pyNN.spiNNaker as p
except:
    import spynnaker.pyNN as p

Section:
The PyNN Neural Network Description Language
An example of this is as follows:
After:
p.run(10)
Add:
v = pop_1.get_v()
spikes = pop_1.getSpikes()

**Comment by Christian-B** [comment]
default parameters of the IF_curr_exp
'tau_refrac': 0.1  NOT 'tau_refrac': 2.0

**Comment by andrewgait** [comment]
Edited and uploaded manual again https://github.com/SpiNNakerManchester/SpiNNakerManchester.github.io/pull/22

**Comment by alan-stokes** [comment]
closed!
