### ISSUE TITLE
RunningPyNNSimulationsonSpiNNaker-LabManual.pdf two missing code lines in exemple

### ISSUE THREAD

**Issue by Ju42** [SpiNNakerManchester/SpiNNakerManchester.github.io#20]
Hi,

I notice that two code lines are missing in the PyNN code example in the following file :
http://spinnakermanchester.github.io/spynnaker/3.0.0/RunningPyNNSimulationsonSpiNNaker-LabManual.pdf

Pylab is use to display two variable evolution (v and spikes). But those variables are never set in this code example. I suggest to add the following lines just after the simulations run call :

```python
v = pop_1.get_v()
spikes = pop_1.getSpikes()
```

**Comment by alan-stokes** [comment]
fixed in master, closing issue
