### ISSUE TITLE
Developer docs do not include spalloc as github reguirement or as dependency

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/SpiNNakerManchester.github.io#23]
See: http://spinnakermanchester.github.io/development/devenv.html

**Comment by alan-stokes** [comment]
i point you at line 

Install other general dependencies via pip: pip install enum34 six "spalloc>=v0.2.2,<v1.0.0" "requests>=2.4.1" jsonschema "rig>=2.0.0,<3.0.0" "quantities>=0.11.1,<=0.11.1" "lazyarray>=0.2.9,<=0.2.9" "appdirs>=1.4.2,<2.0.0" "neo>=0.3.0,<=0.4.1"

in python deps, therefore spalloc is in. issue closed.
