### ISSUE TITLE
http://spinnakermanchester.github.io/development/devenv.html outdated

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/SpiNNakerManchester.github.io#24]
For example:
Spalloc can no longer be pip installed in development

Refers to closed repositories

**Comment by andrewgait** [comment]
Edited the devenv instructions in: https://github.com/SpiNNakerManchester/SpiNNakerManchester.github.io/pull/26 - I think the edit covers this issue?

**Comment by alan-stokes** [comment]
blah blah. closed.
