### ISSUE TITLE
Broken installation instructions

### ISSUE THREAD

**Issue by Paul92** [SpiNNakerManchester/SpiNNakerManchester.github.io#3]
The installation instructions in the following guide:

https://github.com/SpiNNakerManchester/SpiNNakerManchester.github.io/wiki/2015.004%3a-Little-Rascal-%3a-0.2-PyNN-on-SpiNNaker-Installation-Guide#Central

state that the software version should be specified like this:

```
pip install SpiNNMachine=2015.003
```

All of them fail with exceptions like:

```
ValueError: ('Expected version spec in', 'SpiNNMachine=2015.003', 'at', '=2015.003')
```

Installing without a version number (i.e. `pip install SpiNNMachine`) seems to work (reports that SpiNNMachine-2015.3 has been successfully installed).

**Comment by alan-stokes** [comment]
fixed. new release should also refelct these fixes, or at least, wont requre the == for the initial timeframe.
