### ISSUE TITLE
Update developer install to use only Pynn0.9 Neo 0.5

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/SpiNNakerManchester.github.io#30]
Reported by @lplana (thanks)

The developer install still references old versions of PyNN and Neo.

Is it not time to point even new developers against just the latest PyNN and Neo

**Comment by alan-stokes** [comment]
id say so.

**Comment by Christian-B** [comment]
Stripped out references to PyNN0.7 and PyNN0.8.

Linked to older version at: http://spinnakermanchester.github.io/development/pynn8devenv.html  just in case.

**Comment by Christian-B** [comment]
fixed swapped titles.
