### ISSUE TITLE
Check MappingAlgorithms.html is still uptodate

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/SpiNNakerManchester.github.io#37]
http://spinnakermanchester.github.io/common_pages/6.0.0/MappingAlgorithms.html
needs a good checking

Update to not use a rgi example

Is the Json File Form,at still relevant!

**Comment by Christian-B** [comment]
http://spinnakermanchester.github.io/common_pages/6.0.0/MappingExampleFiles.html
All links broken

**Comment by Christian-B** [comment]
<command_line_args> While still tested is not used anywhere

**Comment by Christian-B** [comment]
param_type found in current xml files 
'APPID', 'AppProvenanceFilePath', 'AutoDetectBMPFlag', 'AverageCoresOnChip', 'BMPDetails', 'BitFieldSummary', 'BoardVersion', 'BootPortNum', 'BufferManager', 'CompressedSummary', 'CompressionAsFarAsPos', 'CompressionTargetSize', 'CompressorExecutableTargetsUsed', 'ConnectionHolders', 'CreateAtomToEventIdMapping', 'DSGTimeMs', 'DataInMulticastKeyToChipMap', 'DataInMulticastRoutingTables', 'DataNTimeSteps', 'DataSpecificationTargets', 'DatabaseFilePath', 'DatabaseInterface', 'DatabaseSocketAddresses', 'DatabaseWaitOnConfirmationFlag', 'DisableAdvancedMonitorUsageForDataIn', 'DownedChipsDetails', 'DownedCoresDetails', 'DownedLinksDetails', 'EndUserConfigurableSafetyFactorForTDMAAgenda', 'ErrorMessages', 'ExampleFilePath', 'ExecutableFinder', 'ExecutableTargets', 'ExecutableTypes', 'ExecuteTimeMs', 'ExtractIobufFromBinaryTypes', 'ExtractIobufFromCores', 'ExtractionTimeMs', 'FailedCoresSubsets', 'FirstMachineTimeStep', 'FixedRouteDestinationClass', 'GenerateBitFieldReport', 'GenerateBitFieldSummaryReport', 'GraphProvenanceItems', 'IPAddress', 'IgnoreBadEthernets', 'JavaCaller', 'JsonFolder', 'JsonMachine', 'JsonMachineGraphPath', 'JsonPartitionNKeysMap', 'JsonPlacementsPath', 'JsonRoutingTablesPath', 'LivePacketRecorderParameters', 'LivePacketRecorderParametersToVertexMapping', 'LoadTimeMs', 'MCGathererCoresToAllocate', 'MachineAllocationController', 'MachineHeight', 'MachineJsonPath', 'MachineTimeStep', 'MachineWidth', 'MappingTimeMs', 'MaxCoresUsedOnChip', 'MaxMachineCoreReduction', 'MaxSDRAMSize', 'MemoryApplicationGraph', 'MemoryCompressedRoutingTables', 'MemoryExtendedMachine', 'MemoryExtendedVirtualMachine', 'MemoryExtraMonitorToChipMapping', 'MemoryExtraMonitorVertices', 'MemoryFixedRoutes', 'MemoryIpTags', 'MemoryMCGatherVertexToEthernetConnectedChipMapping', 'MemoryMachine', 'MemoryMachineEdgeNKeysMap', 'MemoryMachineGraph', 'MemoryMachinePartitionNKeysMap', 'MemoryNumberSamplesPerRecordingEntry', 'MemoryPlacements', 'MemoryPlacements2', 'MemoryPreAllocatedResources', 'MemoryReverseIpTags', 'MemoryReverseTags', 'MemoryRoutingInfos', 'MemoryRoutingTableByPartition', 'MemoryRoutingTables', 'MemorySamplingFrequency', 'MemoryTags', 'MemoryTransceiver', 'MemoryVirtualMachine', 'MinCoresUsedOnChip', 'NBoardsRequired', 'NChipsRequired', 'NChipsUsed', 'NPacketsPerTimeWindow', 'NSyncSteps', 'NoSyncChanges', 'NotificationInterface', 'NumberOfCPUCyclesUsedByThePacketReceiveCallback\n', 'NumberOfCpuCyclesByOtherCallbacks', 'PlacementsProvenanceItems', 'PlanNTimeSteps', 'PostSimulationOverrunBeforeError', 'PowerProvenanceItems', 'PowerUsed', 'ProcessorToAppDataBaseAddress', 'ProvenanceItems', 'RegionSizes', 'RemoteSpinnakerUrl', 'RepairMachine', 'ReportFolder', 'ReportWaitingLogsFlag', 'ResetMachineOnStartupFlag', 'RouterBitfieldCompressionReport', 'RouterCompressorBitFieldPercentageThreshold', 'RouterCompressorBitFieldPreAllocSize', 'RouterCompressorBitFieldRetryCount', 'RouterCompressorBitFieldTargetLength', 'RouterCompressorBitFieldTimePerAttempt', 'RouterCompressorBitFieldUseCutOff', 'RouterCompressorProvenanceItems', 'RouterProvenanceItems', 'RouterTableEntriesPerRouter', 'RunTime', 'RunUntilCompleteFlag', 'RunUntilTimeSteps', 'ScampConnectionData', 'SpallocMachine', 'SpallocPort', 'SpallocServer', 'SpallocUser', 'SynapticExpanderReadIOBuf', 'SystemMulticastRouterTimeoutKeys', 'SystemProvenanceFilePath', 'TDMAAgenda', 'TimeScaleFactor', 'TotalRunTime', 'UnCompressedSummary', 'UserCreateDatabaseFlag', 'UserDefinedMaxDelay', 'UsingAdvancedMonitorSupport', 'UsingReinjection', 'WarnMessages', 'WriteBitFieldGeneratorIOBUF', 'WriteCompressorIobuf', 'WriteDataSpeedUpReportsFlag', 'WriteTextSpecsFlag'

**Comment by dkfellows** [comment]
> <command_line_args> While still tested is not used anywhere

I think it _was_ used (or was supposed to be used) when dealing with Rig.

**Comment by Christian-B** [comment]
mapping Algorithms have been removed in the master branch
