### ISSUE TITLE
installation missing bits

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/SpiNNakerManchester.github.io#9]
during the install on a fresh laptop on windows 10, we miss to tell them to install make.

**Comment by rowleya** [comment]
I was pretty sure that this got installed with the Mingw environment... have you installed this?

**Comment by alan-stokes** [comment]
There's no link on the development installation page to the page that
discusses that (that I can find [that said, given results today. It could
be obviously there]). I went to the c development page anyhow and tried to
download it. But that bit we can discuss tomorrow.

**Comment by alan-stokes** [comment]
think this reflects issues with python to c map in the order of events. @sara-es  got caught up on it as well. think there was some proposal back then, but memory faulty

**Comment by andrewgait** [comment]
Pretty sure - without having a Windows environment to test it in - that if you follow the instructions at http://spinnakermanchester.github.io/common_pages/3.0.0/Compiler.html properly then make will be installed properly... would probably be a good idea for someone with access to a Windows environment to test this ahead of the release, though.

**Comment by sara-es** [comment]
If I recall correctly, the only issue that I had (now fixed) was that the order in which instructions were laid out on the website caused some steps to be skipped, if using the quicklinks at the top of the page. I have since clarified on the /development/devenv page

**Comment by alan-stokes** [comment]
think that was what this issue was for originally. missing bits due to the page jumping. but if sara has fixed them, ill kill the issue.
